server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    consumer:
      group-id: consumer-consumers-group
      properties:
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest

    producer:
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: store-consumer-service-client
            client-secret: 7Iqf1S2bESodz36SFISi3n51xgYGoV9S
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/token

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 7000
            readTimeout: 7000

#      oauth2:
#        enabled: true
#        clientRegistrationId: keycloak

keycloak:
  auth-server-url: http://localhost:8070/
  resource: store-consumer-service-client
  realm: store-realm
  ssl-required: external
  use-resource-role-mapping: true
  credentials:
    secret: 7Iqf1S2bESodz36SFISi3n51xgYGoV9S