server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: store-consumer-service-client
            client-secret: 7Iqf1S2bESodz36SFISi3n51xgYGoV9S
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/token

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    listener:
      type: batch
      ack-mode: manual
      concurrency: 3
      poll-timeout: 3000

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: recommendation-group
      properties:
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest
      max-poll-records: 100

kafka:
  dlt-prefix: .dlt
  topics:
    search-all-events: search-all-events