server:
  port: 8099

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/root
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 3000

kafka:
  dlt-prefix: .dlt
  topics:
    review-created: review-created-request
    confirm-review-created: confirm-review-created-response
    cancel-review-created: cancel-review-created-response

    review-updated: review-updated-request
    confirm-review-updated: confirm-review-updated-response
    cancel-review-updated: cancel-review-updated-response

    review-deleted: review-deleted-request
    confirm-review-deleted: confirm-review-deleted-response
    cancel-review-deleted: cancel-review-deleted-response