services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic_pass
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.17.25
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic_pass
    ports:
      - "5601:5601"

  db-catalogue:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5430:5432"

  db-consumer:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5431:5432"

  db-order:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

  db-warehouse:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"

  db-keycloak:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"
    ports:
      #delete ports in future
      - "5434:5432"

  db-synchronization:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5435:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z-cpuv1
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio124
    command: server --console-address ":9001" /export/
    volumes:
      - ./minio/data:/export

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    ports:
      - "9999:8080"
  
  controller-1:
    image: apache/kafka:3.9.0
    container_name: controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  controller-2:
    image: apache/kafka:3.9.0
    container_name: controller-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  broker-1:
    image: apache/kafka:3.9.0
    container_name: broker-1
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - controller-1
      - controller-2

  broker-2:
    image: apache/kafka:3.9.0
    container_name: broker-2
    ports:
      - "39092:9092"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - controller-1
      - controller-2

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - db-keycloak
    ports:
      - "8070:8080"

  redis-catalogue:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
#      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_USER=root
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  redis-insight:
    image: redis/redisinsight:2.66
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - ./redis-insight/data:/data

#  hazelcast:
#    image: hazelcast/hazelcast:5.5
#    environment:
#      - HZ_CLUSTERNAME=dev
#    ports:
#      - 5701:5701
#
#  management-center:
#    image: hazelcast/management-center:5.5
#    ports:
#      - 5801:8080
#    environment:
#      - MC_DEFAULT_CLUSTER=dev
#      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast:5701