services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic_pass
      - xpack.security.enabled=true
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.17.25
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic_pass
    ports:
      - 5601:5601

  logstash:
    container_name: logstash
    image: logstash:7.17.26
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS=http://elasticsearch2222222222:9200
      - XPACK_MANAGEMENT_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MANAGEMENT_ELASTICSEARCH_PASSWORD=elastic_pass
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipelines/pipeline.conf:/usr/share/logstash/config/pipelines/pipeline.conf
      - ./logstash/postgresql-driver.jar:/usr/share/logstash/jars/postgresql-driver.jar
    ports:
      - 9600:9600
      - 9700:9700
      - 5044:5044
      - 5046:5046