services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic_pass
      - xpack.security.enabled=true
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.17.25
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic_pass
    ports:
      - 5601:5601

#  logstash:
#    container_name: logstash
#    image: logstash:7.17.26
#    restart: always
#    depends_on:
#      - elasticsearch
#    volumes:
#      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./logstash/pipeline.conf:/usr/share/logstash/config/pipeline.conf
#      - ./logstash/postgresql-driver.jar:/usr/share/logstash/jars/postgresql-driver.jar
#    ports:
#      - 9600:9600
#      - 9700:9700
#      - 5044:5044
#      - 5046:5046

  postgres:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - 5430:5432

  db-consumer:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z-cpuv1
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio124
    command: server --console-address ":9001" /export/
    volumes:
      - ./minio/data:/export

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 9999:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
  
  controller-1:
    image: apache/kafka:3.9.0
    container_name: controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  controller-2:
    image: apache/kafka:3.9.0
    container_name: controller-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  broker-1:
    image: apache/kafka:3.9.0
    container_name: broker-1
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - controller-1
      - controller-2

  broker-2:
    image: apache/kafka:3.9.0
    container_name: broker-2
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - controller-1
      - controller-2

#  hazelcast:
#    image: hazelcast/hazelcast:5.5
#    environment:
#      - HZ_CLUSTERNAME=dev
#    ports:
#      - 5701:5701
#
#  management-center:
#    image: hazelcast/management-center:5.5
#    ports:
#      - 5801:8080
#    environment:
#      - MC_DEFAULT_CLUSTER=dev
#      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast:5701