server:
  port: 8087

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: store-consumer-service-client
            client-secret: 7Iqf1S2bESodz36SFISi3n51xgYGoV9S
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/token
