server:
  port: 8087

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: store-consumer-service-client
            client-secret: 7Iqf1S2bESodz36SFISi3n51xgYGoV9S
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/token

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 0
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        max.in.flight.requests.per.connection: 5
        linger.ms: 5000