server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    listener:
      type: batch
      ack-mode: manual
      concurrency: 3
      poll-timeout: 3000

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: saga-orchestrator-group
      properties:
#        spring.json.value.default.type: "com.ak.store.common.saga.SagaRequestEvent"
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

saga:
  definitions:
    order-creation:
      name: order-creation
      request-topic: order-creation-request
      compensation-request-topic: cancel-order-request
      compensation-response-topic: cancel-order-response
      steps:
        reserve-funds:
          name: reserve-funds
          timeout: 500
          topics:
            request: payment-reserve-funds-request
            response: payment-reserve-funds-response
            compensation-request: payment-release-funds-request
            compensation-response: payment-release-funds-response

        reserve-products:
          name: reserve-products
          timeout: 500
          topics:
            request: warehouse-reserve-products-request
            response: warehouse-reserve-products-response
            compensation-request: warehouse-release-products-request
            compensation-response: warehouse-release-products-response

        confirm-order:
          name: confirm-order
          timeout: 500
          topics:
            request: confirm-order-request
            response: confirm-order-response
            compensation-request: cancel-order-request
            compensation-response: cancel-order-response

    #------------------------------------------------------------

    user-registration:
      name: user-registration
      request-topic: user-registration-request
      compensation-request-topic: cancel-user-registration-request
      compensation-response-topic: cancel-user-registration-response
      steps:
        user-creation:
          name: user-creation
          timeout: 500
          topics:
            request: user-creation-request
            response: user-creation-response
            compensation-request: cancel-user-creation-request
            compensation-response: cancel-user-creation-response

        user-payment-creation:
          name: user-payment-creation
          timeout: 500
          topics:
            request: user-payment-creation-request
            response: user-payment-creation-response
            compensation-request: cancel-user-payment-creation-request
            compensation-response: cancel-user-payment-creation-response

        confirm-user-creation:
          name: confirm-user-creation
          timeout: 500
          topics:
            request: confirm-user-request
            response: confirm-user-response
            compensation-request: cancel-user-registration-request
            compensation-response: cancel-user-registration-response

    #------------------------------------------------------------

    review-creation:
      name: review-creation
      request-topic: review-creation-request
      compensation-request-topic: cancel-review-creation-request
      compensation-response-topic: cancel-review-creation-response
      steps:
        update-product-rating:
          name: update-product-rating
          timeout: 500
          topics:
            request: add-product-grade-request
            response: add-product-grade-response
            compensation-request: remove-product-grade-request
            compensation-response: remove-product-grade-response

        confirm-review-creation:
          name: confirm-review-creation
          timeout: 500
          topics:
            request: confirm-review-creation-request
            response: confirm-review-creation-response
            compensation-request: cancel-review-creation-request
            compensation-response: cancel-review-creation-response

    #------------------------------------------------------------

    review-update:
      name: review-update
      request-topic: review-update-request
      compensation-request-topic: cancel-review-update-request
      compensation-response-topic: cancel-review-update-response
      steps:
        update-product-rating:
          name: update-product-rating
          timeout: 500
          topics:
            request: update-product-grade-request
            response: update-product-grade-response
            compensation-request: cancel-update-product-grade-request
            compensation-response: cancel-update-product-grade-response

        confirm-review-update:
          name: confirm-review-update
          timeout: 500
          topics:
            request: confirm-review-update-request
            response: confirm-review-update-response
            compensation-request: cancel-review-update-request
            compensation-response: cancel-review-update-response

    #------------------------------------------------------------

    review-deletion:
      name: review-deletion
      request-topic: review-deletion-request
      compensation-request-topic: cancel-review-deletion-request
      compensation-response-topic: cancel-review-deletion-response
      steps:
        update-product-rating:
          name: update-product-rating
          timeout: 500
          topics:
            request: delete-product-grade-request
            response: delete-product-grade-response
            compensation-request: cancel-delete-product-grade-request
            compensation-response: cancel-delete-product-grade-response

        confirm-review-deletion:
          name: confirm-review-deletion
          timeout: 500
          topics:
            request: confirm-review-deletion-request
            response: confirm-review-deletion-response
            compensation-request: cancel-review-deletion-request
            compensation-response: cancel-review-deletion-response