spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    listener:
      type: batch
      ack-mode: manual
      concurrency: 3
      poll-timeout: 3000

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: saga-orchestrator-group
      properties:
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

saga:
  definitions:
    order-creation:
      name: order-creation
      request-topic: order-creation-request
      response-topic: order-creation-response
      timeout: 1200
      steps:
        reserve-funds:
          name: reserve-funds
          timeout: 600
          topics:
            request: payment-reserve-funds-request
            response: payment-reserve-funds-response
            compensation-request: payment-release-funds-request
            compensation-response: payment-release-funds-response

        reserve-products:
          name: reserve-products
          timeout: 600
          topics:
            request: warehouse-reserve-products-request
            response: warehouse-reserve-products-response
            compensation-request: warehouse-release-products-request
            compensation-response: warehouse-release-products-response