server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    listener:
      type: batch
      ack-mode: manual
      concurrency: 3
      poll-timeout: 3000

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: saga-orchestrator-group
      properties:
#        spring.json.value.default.type: "com.ak.store.common.saga.SagaRequestEvent"
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

saga:
  definitions:
    order-creation:
      name: order-creation
      request-topic: order-creation-request
      compensation-request-topic: cancel-order-request
      #todo добавить compensation-response-topic. не закрывать сагу, пока не получу подтверждение об успешности компенсации
      timeout: 300
      steps:
        reserve-funds:
          name: reserve-funds
          timeout: 300
          topics:
            request: payment-reserve-funds-request
            response: payment-reserve-funds-response
            compensation-request: payment-release-funds-request
            compensation-response: payment-release-funds-response

        reserve-products:
          name: reserve-products
          timeout: 300
          topics:
            request: warehouse-reserve-products-request
            response: warehouse-reserve-products-response
            compensation-request: warehouse-release-products-request
            compensation-response: warehouse-release-products-response

        confirm-order:
          name: confirm-order
          timeout: 300
          topics:
            request: confirm-order-request
            response: confirm-order-response
            compensation-request: cancel-order-request
            compensation-response: cancel-order-response

    #------------------------------------------------------------

    user-registration:
      name: user-registration
      request-topic: user-registration-request
      compensation-request-topic: cancel-user-registration-request
      timeout: 300
      steps:
        user-creation:
          name: user-creation
          timeout: 300
          topics:
            request: user-creation-request
            response: user-creation-response
            compensation-request: cancel-user-creation-request
            compensation-response: cancel-user-creation-response

        user-payment-creation:
          name: user-payment-creation
          timeout: 300
          topics:
            request: user-payment-creation-request
            response: user-payment-creation-response
            compensation-request: cancel-user-payment-creation-request
            compensation-response: cancel-user-payment-creation-response

        confirm-user-creation:
          name: confirm-user-creation
          timeout: 300
          topics:
            request: confirm-user-request
            response: confirm-user-response
            compensation-request: cancel-user-registration-request
            compensation-response: cancel-user-registration-response