spring:
  datasource:
    url: "jdbc:postgresql://localhost:5430/postgres?reWriteBatchedInserts=true"
    username: "root"
    password: "root"

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: classpath:ehcache-config.xml
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: jcache
        format_sql: true
        jdbc:
          batch_size: 50
        generate_statistics: true
        order_inserts: true
        order_updates: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB