spring:
  datasource:
    url: "jdbc:postgresql://localhost:5430/postgres"
    username: "root"
    password: "root"
  jpa:
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic_pass

api:
  username: "elastic"
  password: "elastic_pass"
  base:
    url: "http://localhost:9200"