spring:
  datasource:
    url: "jdbc:postgresql://localhost:5430/postgres?reWriteBatchedInserts=true"
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        generate_statistics: true
      order_inserts: true
      order_updates: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic_pass

api:
  username: "elastic"
  password: "elastic_pass"
  base:
    url: "http://localhost:9200"