spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #cache
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: classpath:ehcache-config.xml
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: jcache

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/certs