server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    listener:
      type: batch
      ack-mode: manual
      concurrency: 3
      poll-timeout: 3000

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: synchronization-group
      properties:
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest
      max-poll-records: 100

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

kafka:
  dlt-prefix: .dlt
  topics:
    category-created: category-created
    category-updated: category-updated
    category-deleted: category-deleted

    characteristic-created: characteristic-created
    characteristic-updated: characteristic-updated
    characteristic-deleted: characteristic-deleted

    product-created: product-created
    product-updated: product-updated
    product-deleted: product-deleted
    product-rating-updated: product-rating-updated

elasticsearch:
  indexes:
    product: product