server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    consumer:
      group-id: synchronization-catalogue-group
      properties:
        spring.json.trusted.packages: "com.ak.store.*"
      auto-offset-reset: earliest
      max-poll-records: 100

    producer:
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5