server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: root

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #logs
        format_sql: true
        generate_statistics: true

        #batch
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092

    producer:
      acks: all
      retries: 7
      properties:
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        request.timeout.ms: 15000
        delivery.timeout.ms: 20000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/store-realm/protocol/openid-connect/certs

kafka:
  group-id: order-group
  topics:
    order-created: order-created